name = "27"
author = "ChillRoom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc5403b3dc3ec0178fc04b1d68b0fd9707af33b9196530d0a38d08659fe9a037"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
