name = "27"
author = "ChillRoom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d4d36e1b1893c349c16c7d9fcde2b483591be042860be90beefa8387a5a52fb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
